# Generated by Django 2.2 on 2020-08-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemseller',
            old_name='categoryhere',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='itemseller',
            name='photo_1',
            field=models.ImageField(default=1, upload_to='product_photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
