# Generated by Django 2.2 on 2020-08-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200816_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo_1',
            field=models.ImageField(default=1, upload_to='product_photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
